### ISSUE TITLE
py_gd: DLL load failed

### ISSUE THREAD

**Issue by firasgerges** [NOAA-ORR-ERD/py_gd#13]
from py_gd import *
ImportError: DLL load failed: The specified procedure could not be found.

any ideas?

**Comment by ChrisBarker-NOAA** [comment]
py_gd requires the gd lib to be installed and ready to go.

Did you get any errors building py_gd?

How did you install libgd?

Note: The easiest way to get py_gd running is with the conda packages on our Anaconda channel:

https://anaconda.org/noaa-orr-erd/py_gd

https://anaconda.org/NOAA-ORR-ERD/libgd

conda install -c NOAA-ORR-ERD libgd py_gd 

should do it.

Note that that's a pretty old version of libgd -- there are newer ones no conda-forge, but not for Windows. One of these days, we should get libgd built for Windows on conda-forge. If you have any Windows building expertise -- we'd love a contribution!

**Comment by firasgerges** [comment]
> py_gd requires the gd lib to be installed and ready to go.
> 
> Did you get any errors building py_gd?
> 
> How did you install libgd?
> 
> Note: The easiest way to get py_gd running is with the conda packages on our Anaconda channel:
> 
> https://anaconda.org/noaa-orr-erd/py_gd
> 
> https://anaconda.org/NOAA-ORR-ERD/libgd
> 
> conda install -c NOAA-ORR-ERD libgd py_gd
> 
> should do it.
> 
> Note that that's a pretty old version of libgd -- there are newer ones no conda-forge, but not for Windows. One of these days, we should get libgd built for Windows on conda-forge. If you have any Windows building expertise -- we'd love a contribution!

I installed it using conda install -c https://conda.anaconda.org/noaa-orr-erd py_gd which automatically installed libgd. 
I also tried to download the project and build it. no problem during the build! but whenever I import py_gd the error is raised. 
I am using py_gd as part of the pygnome project! I had to manually put some libraries and DLL in anaconda for what I am doing so it might be the problem, because when running it in virtualenv it works perfectly. I am trying now to re-install anaconda and download all the required packages!

**Comment by ChrisBarker-NOAA** [comment]
> I am using py_gd as part of the pygnome project! I had to manually put some libraries and DLL in anaconda for what I am doing so it might be the problem,

yeah, if you mess with a conda environment by hand, something may go wrong.

> because when running it in virtualenv it works perfectly.

running what? py_gnome without conda is pretty hard to get going ...

> I am trying now to re-install anaconda and download all the required packages!

I"d start (semi) from scratch:

You can actually create an environment for pygnome in one go:

1) make sure you have conda-forge and the NOAA-ORR-ERD channels added.

2) `conda create -n gnome --file conda_requirements.txt`

conda activate gnome

and you should be good to go.

Further questions should probably be on teh py_gnome repo -- we don't expect users to have to mess with py_gd by hand.
