### ISSUE TITLE
Problem to surce erxternal libgd library 

### ISSUE THREAD

**Issue by simomartini** [NOAA-ORR-ERD/py_gd#16]
Hello I followed the instructions to install py_gd on CentOS.
My compilation fails because it can't find the libgd / include folder.
I made 
export LD_LIBRARY_PATH=/to/my/folder/libgd/lib

But when I try to build I get the following message:
`py_gd/py_gd.c:636:16: fatal error: gd.h: No such file or directory
 #include "gd.h"
                ^
compilation terminated.
'

The setup.py does not find the path of the libgd library. How do I include it in the list of libraries searched by setup.py?
I already try without success.

python setup.py config --libraries=/to/my/folder/libgd/lib --include-dirs=/to/my/folder/libgd/include

ad than 

python setup.py build 

Can u help me?

Kind Regards 
Simone

**Comment by ChrisBarker-NOAA** [comment]
Hmm -- I haven't built it on "raw" linux for a long time -- we mostly use conda and conda-forge, which supplies libgd. It builds with a plain `pip install` with the conda-forge libgd.

https://github.com/conda-forge/py_gd-feedstock/

and the built package is here:

https://anaconda.org/conda-forge/py_gd

But it should work on bare bones linux.

Frankly, we've done this in kind of a hacky way, but in setup.py you'll see:

```
elif sys.platform.startswith('linux'):
    library_dirs.append('/usr/local/lib')
    include_dirs.append('/usr/local/include')
```
So this is assuming that the libgd header are in `/usr/local/include`.

I haven't tested it but I think you can add to those on the command line ALMOST like you did. Try:

`python setup.py build --libraries=/to/my/folder/libgd/lib --include-dirs=/to/my/folder/libgd/include`

or

`python setup.py build_ext --libraries=/to/my/folder/libgd/lib --include-dirs=/to/my/folder/libgd/include`

If that doesn't work, then you can patch the setup.py file, and add your paths to include_dirs and  library_dirs by hand.

I think the "proper" way to handle this is to use a setup,cfg file. If you can figure out how to do that, we'd be glad to include it in future versions.

Let us know in any case  if you get it working, and how.

**Comment by simomartini** [comment]
Thanks for the suggestion 

`python setup.py build_ext  --include-dirs=/to/my/folder/libgd/include --library-dirs=/u/to/my/folder/libgd/lib`

works fine for me!
