### ISSUE TITLE
import issues: undefined symbol: gdImageBmp or py_gd.py_gd module not found.

### ISSUE THREAD

**Issue by moisespr123** [NOAA-ORR-ERD/py_gd#17]
Whenever I try to import py_gd (or PyGnome tries to), I get the following error when not using Conda.

```
import py_gd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/py_gd-1.1.2.dev0-py3.6-linux-x86_64.egg/py_gd/__init__.py", line 52, in <module>
    from .py_gd import *
ImportError: /usr/local/lib64/python3.6/site-packages/py_gd-1.1.2.dev0-py3.6-linux-x86_64.egg/py_gd/py_gd.cpython-36m-x86_64-linux-gnu.so: undefined symbol: gdImageBmp
```

Things I tried:
1. Installing the `gd` and `gd-devel` packages.
2. Downloading the libgd file from conda and using those instead of the system repository gd packages

py_gd is successful in being compiled and installed. Output log is below:
```
python setup.py install
not running in conda build
running install
running bdist_egg
running egg_info
creating py_gd.egg-info
writing py_gd.egg-info/PKG-INFO
writing dependency_links to py_gd.egg-info/dependency_links.txt
writing top-level names to py_gd.egg-info/top_level.txt
writing manifest file 'py_gd.egg-info/SOURCES.txt'
reading manifest file 'py_gd.egg-info/SOURCES.txt'
writing manifest file 'py_gd.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/py_gd
copying py_gd/_color_data.py -> build/lib.linux-x86_64-3.6/py_gd
copying py_gd/__init__.py -> build/lib.linux-x86_64-3.6/py_gd
copying py_gd/_cm_listed.py -> build/lib.linux-x86_64-3.6/py_gd
copying py_gd/colors.py -> build/lib.linux-x86_64-3.6/py_gd
creating build/lib.linux-x86_64-3.6/py_gd/test
copying py_gd/test/test_colors.py -> build/lib.linux-x86_64-3.6/py_gd/test
copying py_gd/test/build_checksums.py -> build/lib.linux-x86_64-3.6/py_gd/test
copying py_gd/test/test_gd.py -> build/lib.linux-x86_64-3.6/py_gd/test
copying py_gd/test/intersect_comp.py -> build/lib.linux-x86_64-3.6/py_gd/test
copying py_gd/test/__init__.py -> build/lib.linux-x86_64-3.6/py_gd/test
copying py_gd/test/test_overflow.py -> build/lib.linux-x86_64-3.6/py_gd/test
copying py_gd/test/test_buffer.py -> build/lib.linux-x86_64-3.6/py_gd/test
running build_ext
building 'py_gd.py_gd' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/py_gd
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -I/usr/local/include -I/usr/include/python3.6m -c py_gd/py_gd.c -o build/temp.linux-x86_64-3.6/py_gd/py_gd.o
In file included from /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                 from /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from py_gd/py_gd.c:643:
/usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
py_gd/py_gd.c: In function '__pyx_pf_5py_gd_5py_gd_5Image_24save':
py_gd/py_gd.c:6684:5: warning: implicit declaration of function 'gdImageBmp' [-Wimplicit-function-declaration]
     gdImageBmp(__pyx_v_self->_image, __pyx_v_fp, 0);
     ^
py_gd/py_gd.c: In function '__pyx_pymod_exec_py_gd':
py_gd/py_gd.c:32963:3: warning: implicit declaration of function 'gdVersionString' [-Wimplicit-function-declaration]
   __pyx_t_3 = gdVersionString();
   ^
py_gd/py_gd.c:32963:13: warning: assignment makes pointer from integer without a cast [enabled by default]
   __pyx_t_3 = gdVersionString();
             ^
gcc -pthread -shared -Wl,-z,relro -g build/temp.linux-x86_64-3.6/py_gd/py_gd.o -L/usr/local/lib -L/usr/lib64 -lgd -lpython3.6m -o build/lib.linux-x86_64-3.6/py_gd/py_gd.cpython-36m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/py_gd
copying build/lib.linux-x86_64-3.6/py_gd/py_gd.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/py_gd
creating build/bdist.linux-x86_64/egg/py_gd/test
copying build/lib.linux-x86_64-3.6/py_gd/test/test_colors.py -> build/bdist.linux-x86_64/egg/py_gd/test
copying build/lib.linux-x86_64-3.6/py_gd/test/build_checksums.py -> build/bdist.linux-x86_64/egg/py_gd/test
copying build/lib.linux-x86_64-3.6/py_gd/test/test_gd.py -> build/bdist.linux-x86_64/egg/py_gd/test
copying build/lib.linux-x86_64-3.6/py_gd/test/intersect_comp.py -> build/bdist.linux-x86_64/egg/py_gd/test
copying build/lib.linux-x86_64-3.6/py_gd/test/__init__.py -> build/bdist.linux-x86_64/egg/py_gd/test
copying build/lib.linux-x86_64-3.6/py_gd/test/test_overflow.py -> build/bdist.linux-x86_64/egg/py_gd/test
copying build/lib.linux-x86_64-3.6/py_gd/test/test_buffer.py -> build/bdist.linux-x86_64/egg/py_gd/test
copying build/lib.linux-x86_64-3.6/py_gd/_color_data.py -> build/bdist.linux-x86_64/egg/py_gd
copying build/lib.linux-x86_64-3.6/py_gd/__init__.py -> build/bdist.linux-x86_64/egg/py_gd
copying build/lib.linux-x86_64-3.6/py_gd/_cm_listed.py -> build/bdist.linux-x86_64/egg/py_gd
copying build/lib.linux-x86_64-3.6/py_gd/colors.py -> build/bdist.linux-x86_64/egg/py_gd
byte-compiling build/bdist.linux-x86_64/egg/py_gd/test/test_colors.py to test_colors.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/py_gd/test/build_checksums.py to build_checksums.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/py_gd/test/test_gd.py to test_gd.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/py_gd/test/intersect_comp.py to intersect_comp.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/py_gd/test/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/py_gd/test/test_overflow.py to test_overflow.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/py_gd/test/test_buffer.py to test_buffer.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/py_gd/_color_data.py to _color_data.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/py_gd/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/py_gd/_cm_listed.py to _cm_listed.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/py_gd/colors.py to colors.cpython-36.pyc
creating stub loader for py_gd/py_gd.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/py_gd/py_gd.py to py_gd.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying py_gd.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying py_gd.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying py_gd.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying py_gd.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying py_gd.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/py_gd-1.1.2.dev0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing py_gd-1.1.2.dev0-py3.6-linux-x86_64.egg
removing '/usr/local/lib64/python3.6/site-packages/py_gd-1.1.2.dev0-py3.6-linux-x86_64.egg' (and everything under it)
creating /usr/local/lib64/python3.6/site-packages/py_gd-1.1.2.dev0-py3.6-linux-x86_64.egg
Extracting py_gd-1.1.2.dev0-py3.6-linux-x86_64.egg to /usr/local/lib64/python3.6/site-packages
py-gd 1.1.2.dev0 is already the active version in easy-install.pth

Installed /usr/local/lib64/python3.6/site-packages/py_gd-1.1.2.dev0-py3.6-linux-x86_64.egg
Processing dependencies for py-gd==1.1.2.dev0
Finished processing dependencies for py-gd==1.1.2.dev0
```

------------------

On another note, somehow cleaning and rebuilding broke the install?

```
import py_gd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/py_gd/py_gd/__init__.py", line 52, in <module>
    from .py_gd import *
ModuleNotFoundError: No module named 'py_gd.py_gd'
```

Our client requires us to not use conda, which is why I'm doing this process of installing everything as native as possible.

**Comment by ChrisBarker-NOAA** [comment]
Mysterious.

however, looking in your build log, I see:

```
py_gd/py_gd.c: In function '__pyx_pf_5py_gd_5py_gd_5Image_24save':
py_gd/py_gd.c:6684:5: warning: implicit declaration of function 'gdImageBmp' [-Wimplicit-function-declaration]
     gdImageBmp(__pyx_v_self->_image, __pyx_v_fp, 0);
```
Since you were getting a symbol error with `gdImageBmp` that may be the issue here -- the compiler / linker you're using may not be friendly to the "implicit declaration" -- not that I know what it means but it might be relevant.

I'll try to take a look at the Cython and see if I can see anything.

Other things so try:

can you run the py_gd tests? if so, what happens, you should be able to do that by either:

```
cd py_gd/test
pytest
```
(pip install pytest first)

or:

```
pytest --pyargs py_gd
```
from anywhere.

As for the broken re-install, try again with pip:

pip install ./

pip will look for the setup.py, and run it, with a few things tweaked differently.

You also might try doing all that in a virtual environment of some sort, so keep things clean :-)

**Comment by ChrisBarker-NOAA** [comment]
compiling on OS-X does not show that same warning with `gdImageBMP` :-(

And looking at the Cython code, we are handling it exactly the same as the other image formats, PNG, etc.

A few more details that might help

What versions of:

Python

Cython

libgd

gcc

are you using?

**Comment by ChrisBarker-NOAA** [comment]
Think abou this a bit more (sorry I don't' have a Linux system handy, and it's been a while :( ), but:

I can't imagine there's been a version of libgd that hasn't had BMP support for a long time. (there was a BMP bug not too long ago, but I doubt that's the issue here). And you tired the same version as the conda-forge build is using.

Which means there's something going on with linking -- as it builds OK, it's finding libgd at build time, but apparently not at run time. I would have thought that it would give you a linking error, but as the extension is a shared lib, maybe not?? it could be arbitrary that gdImageBMP was the first symbol it looked for.

NOTE: You might try an "editable" install first, to make it easier to test things:

`pip install -e ./`

Some things to try:

1) make sure that libgd got installed in a "standard" place -- hard to imagine it didn't if you got it from the system package manager, but if you built it yourself, maybe not.

2) run `ldd` on the py_dv extension:

https://www.howtoforge.com/linux-ldd-command/

something like:

`ldd py_gd/py_gd.cpython-36m-x86_64-linux-gnu.so`

That .so should be in the build dir

ldd will tell you what the extension is linked to -- it should point to the libgd shared libs, and you can then make sure that those are where they are expected.

@NaomiWilkins-NOAA:  Are you set up to built / test on LInux? This would be a lot easier to debug that way :-)

Finally -- see if the resolution to #16 helps -- not the same symptoms, but maybe?

**Comment by moisespr123** [comment]
Hi Chris, I tried a clean install in my environment again and this time I got forward with a bunch of dependency issues. Thanks to the ldd command I found out that the packages were on another directory, so I was installing `libgd.so.3` at the wrong location. I was then able to install the correct packages for the distro I'm using and got this library to import as well as pygnome.

**Comment by ChrisBarker-NOAA** [comment]
Excellent!

If you could summarize the steps you used to successfully install, it would be greta to have a record of that in this issue for future reference.

Also: is there some configuration we could/should add to the build scripts that would help?

**Comment by moisespr123** [comment]
Sure, the distro is CentOS 7, so the packages are out of date nowadays. I pulled the `libgd-2.1.1-5.tar.bz2` from the `libgd` Conda repo. The tar  `/include` files should be in `/usr/include` but the `/lib/libgd.so.3` file needed to be in `/lib64` (applies to the other modules). 

Since CentOS 7 contains outdated packages, `libpng` and `zlib` needed to be downloaded from the CentOS 8 repo (I just manually downloaded the rpm files and installed them with the rpm command, `rpm --force -i the_library_rpm.rpm`. Not a good idea as it may break something else but for the purpose of `py_gd` and `pygnome`, this was the solution to importing and running it successfully.

The only external library download besides `libgd` was `libjpeg`, since the CentOS 8 package in CentOS 7 complained about libc6. Just downloading a precompiled version of the `libjpeg.so.8` file should do it.

**Comment by ChrisBarker-NOAA** [comment]
Great, thanks.

libgd is used by PHP, so I'm a bit surprised that a recent version isn't easily available for CentOS 7, but I'm glad you found something that worked.

Note that conda just grabs the tarball from gitHub, so that should be possible, too.
