### ISSUE TITLE
Problem with py_gd.Image

### ISSUE THREAD

**Issue by bhlevca** [NOAA-ORR-ERD/py_gd#21]
HI Chris I am trying to create a pip version of the py_gd package because I dislike conda/Anaconda because many packages are old or unmaintained.   

I managed to run nicely WebGnome on windows using only pip packages by converting the conda_requirements.txt to requirements.txt and have 2 packages that I needed to get the sources and installed them with python setup.py : griddle and py_gd. Both yours. I had no probles with griddle but had issues with py_gd due to the many dependencies. I used vcpkg from github hat bring nicely all the dependencies and update the `library_dirs` accordingly:
```
if sys.platform.startswith('win'):
    print(" >>**<< SYS.PREFIX:%s", sys.prefix)
    # need the library and include for Windows Anaconda... <PREFIX>/Library
    include_dirs.append(os.path.join(sys.prefix, r'Library\include'))
    include_dirs.append(os.path.join(sys.prefix, r'..\vcpkg\installed\x64-windows\include'))
    print(" >>**<< INCLUDE PATH: ", os.path.join(sys.prefix, r'..\vcpkg\installed\x64-windows\lib')) 
    # dlls go in bin, rather than lib (??)
    library_dirs.append(os.path.join(sys.prefix, r'Library\lib'))
    library_dirs.append(os.path.join(sys.prefix, r'..\vcpkg\installed\x64-windows\lib'))
    #library_dirs.append(os.path.join(sys.prefix, r'..\vcpkg\installed\x64-windows\bin'))
    print(" >>**<< LIB PATH:", os.path.join(sys.prefix, r'..\vcpkg\installed\x64-windows\lib')) 
```

I also made the change in the `__init__.py` :
` libpath = "C:\\MECP\\WebGnome\\vcpkg\\installed\\x64-windows\\bin"`

and 
```
 try:
         libpng = ctypes.cdll.LoadLibrary(os.path.join(libpath,'libpng16.dll'))
         zlib = ctypes.cdll.LoadLibrary(os.path.join(libpath,'zlib1.dll'))
         libgd = ctypes.cdll.LoadLibrary(os.path.join(libpath,'libgd.dll'))
 except WindowsError as err:
         raise WindowsError("Can't find dlls for libgd, libpng, and libz.\n"
                            "This kludge is only written to support Anaconda installs")
```

All went well and WebGnome works fine except I cannot uplpoad the shore boundaries because it complains that `py_gd.Image `  does not exist. 

I did some investigation and I can see that py_gd.pxd does not "export" the class Image. 

Could you help me a little to understand what is going on here, why is WebGnome asking for the Image class when you don't export it? Thanks.

**Comment by ChrisBarker-NOAA** [comment]
>  I dislike conda/Anaconda because many packages are old or unmaintained.

Do take a look at the conda-forge project -- it is very active and well maintained -- which is why we rely on it for PyGNOME: 

https://conda-forge.org/

That being said, having our packages available via pip is a worthy goal, we just haven't had the bandwidth to do it. So thanks for working on this.

> ...  pip packages by converting the conda_requirements.txt to requirements.txt

If you contribute that via PR, we'd be glad to include it -- though maybe call it pip_requirements.txt

> I have 2 packages that I needed to get the sources and installed them with python setup.py

I'm a bit surprised -- there are a few in there that certainly didn't used to be available via pip -- anything that has to be compiled and particularly relies on third-party C libs can be a problem -- but great! 

NOTE: are you using recent versions? ideall the develop branch to get the most recent.

> gridded 

Yes, gridded is pure Python, so should be easy --- in fact, I thought we had it up on PyPi already , but I guess haven't maintained that. If you'd like to contribute to making that available on PyPi, we'd be happy for the help. But it should be pip-installable from the gitHub release  in any case:

```
python -m pip install https://github.com/NOAA-ORR-ERD/gridded/archive/v0.3.0.tar.gz
```

(or you can install from a branch on git as well -- see the pip docs)

>  had issues with py_gd due to the many dependencies.

py_gd is trickier -- not only does it need to be compiled, but it relies on the libgd, which is not easy (or want) to get for Windows and Mac platforms. I suppose we could build a wheel with statically linked libgd, but libgs itself relies on a bunch of other libs -- not a trivial task. But if you can contribute -- we'd gladly accept !

>  I used vcpkg from github hat bring nicely all the dependencies and update the library_dirs accordingly:

vcpkg may well be a really useful solution for this -- so libgd and all its dependencies are available?  nice!

If you can make any changes to the source to find the libs generic (i.e. still work with a conda install) then we'll include those, too.

> I cannot upload the shore boundaries because it complains that py_gd.Image does not exist.

Yes -- PyGNOME uses py_gd to rasterize the shoreline.

> I did some investigation and I can see that py_gd.pxd does not "export" the class Image.

py_gd is a Cython package:

.pxd files are declaration files for Cython -- they tell the Cython compiler what it needs to know to generate the C code.

The `py_gd.Image` class is a Python class, written in the Cyton source code: py_gd.pyx. When py_gd is built, it should be provided in the py_gd namespace.

if py_gd is successfully built and installed, you should be able to do:

import py_gd
im = py_gd.Image

The first thing I"d do if you think yo'uve got it built and installed is to run teh tests. Either from the source:

```
cd py_gd/test
pytest
```
Or, if teh package is installed, from anywhere:

```
pytest --pyargs py_gd
```

All this hassle is a hint as to whet we went with conda :-)

**Comment by bhlevca** [comment]
Thanks for your reply 

Yes, vcpkg has all the dependencies needed for building libgd and libgd is complied properly
when I do a ` pip install .` or `python setup.py install`  the py_gd packages compiles and print no error 

```
>>> import py_gd
>>> im = py_gd.Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'py_gd' has no attribute 'Image'
```

if I do a `dir` on the package there is nothing in there that is related to GD:

```
>>> print(dir(py_gd))
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'ctypes', 'libgd', 'libpath', 'libpng', 'os', 'sys', 'zlib']

```

So the dependencies are included but nothing related to  py_gd.   I wonder what is causing the py_gd stuff not to be included?
I was wondering if you have any ideas about how to tackle the problem

**Comment by bhlevca** [comment]
I found the problem in my __init__,py . No The py_gd installs and works correctly correctly.

I hope that I will have some time to pull request. I made a few modifications, mostly  in the setup.py and __init__.py
PIP can install correctly now and with these modifications it could be installed directly form github.  At the moment I made all the dependencies manually  with vcpkg. It will be needed the automation of this process. 

In worst case scenario, if I can't make the time, or I am unable to do the automation, would you be interested to give you my files?  Thanks.

**Comment by ChrisBarker-NOAA** [comment]
I'm glad you worked it out.

I'm still not sure what bet practice is for this kind of thing -- Ideally we'd build a wheel.

if you can figure out how to either statically link or bundle the libs in teh wheel, that would be great.

But yes, we'll take whatever you have time for -- even if it's just instructions.

Closing this issue for now -- feel free to re-open if you have other questions.

-Chris

**Comment by bhlevca** [comment]
I chose the easier route for now as I am not an expert in python packaging but just stubborn to do thing until they work. I could not use `conda` because I use a slightly modified version of `WebGnome `that uses `DHI`'s MIKE for generating the hydrodynamic files. We did an automation with getting input data, HD simulation and converiting the output to `netCDF`.  From here `WebGnome` takes the lead.  There is a `conda `package for MIKE that is called `mikeio `but is poorly maintained whereas `mikeio` in `PYPI` is always up to date. Therefore I chose to do everything with `pip`.

Here are the steps that I used to make everything work with pip only .

1. I created a Python environment with:
 ```
 pip install virtualenv
 virtualenv WebGnomeEnv
 source WebGnomeEnv/bin/activate   (if you use the GIT bash installed in Windows
```
  or
```
 WebGnomeEnv/bin/activate.bat 
```
2. Download all the repositories 
- git clone –branch develop https://github.com/NOAA-ORR-ERD/adios_oil_database.git
- git clone --branch mikehd https://github.com/NOAA-ORR-ERD/WebGnomeAPI.git
- git clone --branch mikehd https://github.com/NOAA-ORR-ERD/PyGnome.git
- git clone --branch mikehd https://github.com/NOAA-ORR-ERD/WebGnomeClient.git

3. I converted all the conda_requirements.txt to requirements.txt for: PyGnome, WebGnomeAPI, and adios_oil_database

an example for PyGome is below, in general the file is very similar in syntax 

```
# Documents the pip packages required for PyGnome
#  this covers py_gnome and the oil_library
#  
#  install with:
#    pip install -r requirements.txt
#
#  or create an environmemnt:
#    conda create -n gnome --file conda_requirements.txt
# These packages would all be in one of the following channels:
# defaults
# conda-forge
# NOAA-ORR-ERD

#python == 3.8.0

# for SpatialRelease
trimesh
shapely
pyproj
mapbox_earcut # from NOAA_ORR_ERD channel -- not working

setuptools
gitpython
numpy
scipy
gsw
psutil
progressbar
pyzmq
geojson
colander

tblib # still needed for child process exception handling.

netCDF4
# awesome-slugify>=1.6.5 # required for adios_db
# regex
# unidecode>=0.04.19
pyshp


# NOAA maintained packages
# gridded == 0.3.0 -> installed from sources
pynucos
cell_tree2d
py_gd #>= 1


# required for building
cython

# needed to run tests
pytest
pytest-cov
pytest-timeout
testfixtures

# nice to have for development, not required to run
matplotlib
ipython
notebook # this gets you Jupyter notebook without all the QT stuff

# required to build docs
sphinx
sphinx_rtd_theme
nbsphinx
```

For the other packages:  WebGnomeAPI, and adios_oil_database the conversion is similar, main difference is that `==` needs to be converted to `=`
 
4. Notable  difference are `gridded ` and `py_gd`
 `gridded` is install very simple with  `pip install https://github.com/NOAA-ORR-ERD/gridded.git`


5. Installation of `py_gd` is complicated due to its dependencies on external libraries. I solved the problem with dynamic libraries and modified the `setup.py` and `__init__.py` to include and load the libraries.

First  we need to install the dependencies and [VCPKG](https://github.com/microsoft/vcpkg) has all the libraries we need.
Please follow the instructions from the [README](https://github.com/microsoft/vcpkg/README.md) file to install and configure.

Below  I will paste files the 2 files I needed to modify to make this work and also and attach them as `TXT` and `pyproject.toml` and `MANIFEST.in`

setup.py:

```
#!/usr/bin/env python

"""
setup.py script for the py_gd package

Tested with:
  conda (with conda-forge libgd) on OS_X

On Windows, MacOS and Linux (CentoOS 7)

libgd is assumed to be installed (and its dependencies) already.
The conda package on conda-forge is a good way to get it:

https://anaconda.org/conda-forge/libgd

"""

import sys
import os
import glob
import shutil

from setuptools           import find_packages, setup
#from setuptools           import Command
from setuptools.extension import Extension

#from setuptools import setup, Extension, find_packages
from distutils.command.clean import clean

from Cython.Build import cythonize
#from Cython.Distutils import build_ext

import numpy  # for the include dirs...

# could run setup from anywhere
SETUP_PATH = os.path.dirname(os.path.abspath(__file__))

include_dirs = [numpy.get_include()]
library_dirs = []
libraries = ['gd', 'libgd']
compile_args = []
link_args = []

# File extensions to be considered as data files. (Literal, no wildcards.)
#dataexts  = (".py",  ".pyx", ".pxd",  ".c", ".cpp", ".h",  ".sh",  ".lyx", ".tex", ".txt", ".pdf")

# Standard documentation to detect (and package if it exists).
#standard_docs     = ["README", "LICENSE", "TODO", "CHANGELOG", "AUTHORS"]  # just the basename without file extension
#standard_doc_exts = [".md", ".rst", ".txt", ""]  # commonly .md for GitHub projects, but other projects may use .rst or .txt (or even blank).

if sys.platform.startswith('win'):
    print(" >>**<< SYS.PREFIX:%s", sys.prefix)
    # need the library and include for Windows Anaconda... <PREFIX>/Library
    incpath = r'..\vcpkg\installed\x64-windows\include'
    include_dirs.append(os.path.join(sys.prefix, r'Library\include'))
    include_dirs.append(os.path.join(sys.prefix, incpath))
    print(" >>**<< INCLUDE PATH: ", os.path.join(sys.prefix, incpath)) 
    # dlls go in bin, rather than lib (??)
    libpath = r'..\vcpkg\installed\x64-windows\lib'
    library_dirs.append(os.path.join(sys.prefix, r'Library\lib'))
    library_dirs.append(os.path.join(sys.prefix, libpath))
       
    compile_args.append('/EHsc')
    link_args.append('/MANIFEST')
    #link_args.append('/WHOLEARCHIVE')
elif sys.platform.startswith('linux'):
    library_dirs.append('/usr/local/lib')
    include_dirs.append('/usr/local/include')

# crazy kludge to find include dir in a conda build:
# check if we are running conda build:
if 'CONDA_BUILD' in os.environ:
    print("running in conda build, adding include dir")
    prefix = os.environ['PREFIX']
    include_dirs.append(os.path.join(prefix, 'include'))
    print("added:", include_dirs[-1])
else:
    print("not running in conda build")


class cleanall(clean):
    description = ("cleans files generated by 'develop' mode and files "
                   "autogenerated by cython")

    def run(self):
        # call base class clean
        clean.run(self)

        # clean remaining cython/cpp files
        t_path = [os.path.join(SETUP_PATH, 'py_gd')]
        exts = ['*.so', 'cy_*.pyd', 'cy_*.cpp', 'cy_*.c']

        for temp in t_path:
            for ext in exts:
                for f in glob.glob(os.path.join(temp, ext)):
                    print("Deleting auto-generated file: {0}".format(f))
                    try:
                        if os.path.isdir(f):
                            shutil.rmtree(f)
                        else:
                            os.remove(f)
                    except OSError as err:
                        print("Failed to remove {0}. Error: {1}"
                              .format(f, err))
                        # raise

        rm_dir = ['py_gd.egg-info', 'build']
        for dir_ in rm_dir:
            print("Deleting auto-generated directory: {0}".format(dir_))
            try:
                shutil.rmtree(dir_)
            except OSError as err:
                if err.errno != 2:  # ignore the not-found error
                    raise


# This setup requires libgd and its dependent libs
# It expects to find them in the "usual" locations
#   or where conda puts it...

ext_modules = [Extension(name="py_gd.py_gd",
                         sources=["py_gd/py_gd.pyx"],
                         include_dirs=include_dirs,
                         library_dirs=library_dirs,
                         libraries=libraries,
                         extra_compile_args=compile_args,
                         extra_link_args=link_args,
                         )]
 
ext_modules = cythonize(
                  ext_modules,
                  compiler_directives={'language_level': 3})

ext_modules = cythonize("py_gd/py_gd.pyx")
def get_version():
    """
    get version from __init__.py
    """
    with open(os.path.join("py_gd", "__init__.py")) as initfile:
        for line in initfile:
            line = line.strip()
            if line.startswith("__version__"):
                version = line.split("=")[1].strip(' "')
                return version

with open("README.md", 'r') as f:
    long_description = f.read()

setup(name="py_gd",
      version=get_version(),
      description="python wrappers around libgd graphics lib",
      long_description=long_description,
      author="Christopher H. Barker",
      author_email="chris.barker@noaa.gov",
      url="https://github.com/NOAA-ORR-ERD/py_gd",
      license="Public Domain",
      keywords="graphics cython drawing",
      cmdclass={'cleanall': cleanall},
      ext_modules=ext_modules,
      zip_safe=False,  # dont want a compiled extension in a zipfile...
      packages=['py_gd', 'py_gd.test'],
      #packages=find_packages(),
      include_dirs=[numpy.get_include()],
      #package_data = {"" : ["*.pyx", "*.pxd", "*.c", "*.h"]},
      #package_dir={'py_gd':  'py_gd'},
      include_package_data=True,
      python_requires='>=3.8',
      platforms=["Windows", "Linux"],
      classifiers=["Development Status :: 2 - Pre-Alpha",
                   "Topic :: Utilities",
                   "License :: Public Domain",
                   "Intended Audience :: Developers",
                   "Operating System :: OS Independent",
                   "Programming Language :: Cython",
                   "Programming Language :: Python :: 3 :: Only",
                   "Programming Language :: Python :: Implementation :: CPython",
                   "Topic :: Multimedia :: Graphics",
                   ],
      )
```

and `__init__.py` from the py_gd subdirectory:

```
#!/usr/bin/env python

"""
py_gd package -- wrappers around the libgd graphics drawing package

The "real" code is in the cython file: py_gd.pyx

This __init__ does some kludges to load libraries, and then does an

from .py_gd import *
"""

import sys
import os
import ctypes
__version__ = "2.0.3"

print(">>> initalize PY_GD:", os.getcwd())

if sys.platform.startswith('win'):
    # This only works for Anaconda / miniconda
    # On other  systems, logic needs to be added here.
    libpath = os.path.join(os.path.split(sys.executable)[0], "Library", "bin")
    print(">>> LIBPATH:", libpath)
    libpath = "C:\\MECP\\WebGnome\\vcpkg\\installed\\x64-windows\\bin"
    print(">>> LIBPATH 2:", libpath)
    # UGLY kludge for Windows: load the libgd dll with ctypes so it can be used by the extension
    # import ctypes
    # # note: need to load up the dependencies, too
    # #       this is a serious kludge!
    try:
         libpng = ctypes.cdll.LoadLibrary(os.path.join(libpath,'libpng16.dll'))
         zlib = ctypes.cdll.LoadLibrary(os.path.join(libpath,'zlib1.dll'))
         libgd = ctypes.cdll.LoadLibrary(os.path.join(libpath,'libgd.dll'))
    except WindowsError as err:
         raise WindowsError("Can't find dlls for libgd, libpng, and libz.\n"
                            "This kludge is only written to support Anaconda installs")

    # alternative ugly kludge: add lib dir to PATH:
    #if not (os.path.isfile(os.path.join(libpath, 'libpng16.dll')) and
    #        os.path.isfile(os.path.join(libpath, 'zlib.dll')) and
    #        os.path.isfile(os.path.join(libpath, 'libgd.dll'))):
    #    raise RuntimeError("Can't find dlls for libgd, libpng, and libz.\n"
    #                       "This kludge is only written to support Anaconda installs\n",
    #                       "you may need to add some logic for other library locations",
    #                       )
    if not (os.path.isfile(os.path.join(libpath, 'libpng16.dll')) and
            os.path.isfile(os.path.join(libpath, 'zlib1.dll')) and
            os.path.isfile(os.path.join(libpath, 'libgd.dll'))):
        raise RuntimeError("Can't find dlls for libgd, libpng, and libz.\n"
                           "This kludge is only written to support Anaconda installs\n",
                           "you may need to add some logic for other library locations",
                           )
    os.environ['PATH'] = libpath + os.pathsep + os.environ['PATH']
try:
    from .py_gd import *
    

except ImportError as err:
    if str(err).startswith("DLL load failed:"):
        if not (os.path.isfile(os.path.join(libpath, 'libpng16.dll')) and
                os.path.isfile(os.path.join(libpath, 'zlib1.dll')) and
                os.path.isfile(os.path.join(libpath, 'libgd.dll'))):
            raise RuntimeError("Can't find dlls for libgd, libpng, and libz.\n"
                               "This kludge is only written to support Anaconda installs\n",
                               "you may need to add some logic for other library locations",
                               )
        else:
            raise
    else:
        raise
    print(err.args)
```

I installed `py_gd` after modifying the files with: `python setup.py install` or ` pip install .` from the root directory.

I forgot to mention that the first step was to install [Visual Studio 2022 - free edition](https://visualstudio.microsoft.com/downloads/) 

Now I get the boundaries in WebGnome with no problems. Please let me know if it works for you. If I find some more time I will try to find a solution for static libraries.

[__init__.TXT](https://github.com/NOAA-ORR-ERD/py_gd/files/8413473/__init__.TXT)
[setup.TXT](https://github.com/NOAA-ORR-ERD/py_gd/files/8413474/setup.TXT)
[pyproject.TXT](https://github.com/NOAA-ORR-ERD/py_gd/files/8413475/pyproject.TXT)
[MANIFEST.TXT](https://github.com/NOAA-ORR-ERD/py_gd/files/8413478/MANIFEST.TXT)

**Comment by bhlevca** [comment]
Note: in `__init__.py` the path needs to be made relative as I did in setup.py, but it is still kludgy, perhaps an environmental variable would be the best.

**Comment by bhlevca** [comment]
I created a fork that works with VCPKG/Visual C compiler and installs with PIP
[https://github.com/bhlevca/py_gd](https://github.com/bhlevca/py_gd)
