### ISSUE TITLE
Reference for text size

### ISSUE THREAD

**Issue by jay-hennen** [NOAA-ORR-ERD/py_gd#5]
Right now there's no information about how large the fonts used in draw_text() are. This, in lieu of specific alignment or text-box origin flags, makes it very difficult to offset text appropriately along the right and bottom edge of images

**Comment by ChrisBarker-NOAA** [comment]
Did you find a solution? It seems we could hard-code something in py_gd.

Also -- it looks like there is no way in gd itself to specify any other alignment -- but it would be nice to add that to py_gd, maybe and "align" flag or something, that could:

Be "top", "center",  "Bottom" -- and then it would use the pre-figured out sizes of th fonts to shift the alignment for you. 

If they are fixed-width fonts, then you could also do "left | center | right".

In the longer term it would be nice to support TrueType fonts, but not sure we want to go there just yet.
