### ISSUE TITLE
Runtime libraries on LInux not on path

### ISSUE THREAD

**Issue by jay-hennen** [NOAA-ORR-ERD/py_gd#6]
If you cannot get libgd from your package manager and build/install it from the repository yourself, the .so files are placed in /usr/local/lib, which is not on the PATH or LD_LIBRARY_PATH by default. If you follow the instructions and 'export LD_LIBRARY_PATH="/usr/local/lib"', you can build and run py_gd as long as that is defined.

In short, /usr/local/lib needs to be on the PATH or LD_LIBRARY_PATH to both compile and run py_gd if libgd is built manually.

**Comment by ChrisBarker-NOAA** [comment]
@jay-hennen: I think this is in the Linux install direction in the README -- but could you make sure it's clear? 

Thanks.

**Comment by jay-hennen** [comment]
It is clear for the installation, but it's not clear that /usr/local/lib needs to *stay* on the LD_LIBRARY_PATH, I think

**Comment by ChrisBarker-NOAA** [comment]
Updated readme a bit more -- should be good to go.
