### ISSUE TITLE
"setup.py build" fails on Ubuntu 14.04 

### ISSUE THREAD

**Issue by ubernaut** [NOAA-ORR-ERD/py_gd#7]
```
py_gd/py_gd.pyx:1136:30 Cannot convert 'FILE *' to Python object

 File "setup.py", line 123, in <module>
    ext_modules = cythonize(ext_modules),
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 798, in cythonize
    cythonize_one(*args[1:])
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 915, in cythonize_one
    raise CompileError(None, pyx_file)

```

Got here through trying to install the latest version of pygnome when pip install -r requirements.txt failed for py_gd. 

Tried the git version and also tried to building libgd 2.1.1 to see if that would help.  

Maybe it's the cython version? 0.20.1post0

Here is the complete output:

http://pastebin.com/9pb3GMpH

**Comment by ChrisBarker-NOAA** [comment]
You definitely need libgd 2.1.1, older versions won't work.

But it does look like it's failing at the Cython level, before it even
reads the libgd headers. I'm not sure what version of Cython we've been
using, but try a more recent one. The latest is 0.23.4. I'm not sure we've
tried it with that version yet, but definitely a recent one.

I suppose we should distribute the Cython generated code, but we've been
focusing on providing conda builds instead...



On Feb 24, 2016, at 5:12 PM, ubernaut <notifications@github.com> wrote:

py_gd/py_gd.pyx:1136:30 Cannot convert 'FILE *' to Python object

 File "setup.py", line 123, in <module>
    ext_modules = cythonize(ext_modules),
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py",
line 798, in cythonize
    cythonize_one(*args[1:])
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py",
line 915, in cythonize_one
    raise CompileError(None, pyx_file)


Got here through trying to install the latest version of pygnome when pip
install -r requirements.txt failed for py_gd.

Tried the git version and also tried to building libgd 2.1.1 to see if that
would help.

Maybe it's the cython version? 0.20.1post0

Here is the complete output:

http://pastebin.com/9pb3GMpH

—
Reply to this email directly or view it on GitHub
<https://github.com/NOAA-ORR-ERD/py_gd/issues/7>.

**Comment by ChrisBarker-NOAA** [comment]
OK, I just checked, the we're using Cython 0.23.4

It probably works with older ones, but that all that old....

**Comment by ChrisBarker-NOAA** [comment]
this has been working for a while now ...
